### PR TITLE
Fix file not found error with latest dotnet 6.0.2 and pack issue

### PR DESCRIPTION
**Pull request by Kurounin**

### CODE REVIEW

**Comment by Kurounin** [comment]
@alirezanet Can you please merge this and make a new release? It fixes 2 issues I encountered:
- file not found error when not publishing symbols using the latest dotnet 6.0.2 (explained here https://github.com/NuGet/Home/issues/11601#issuecomment-1054883488)
- explicit and transient dependencies are not packed when adding them in `AddGenerationTimeReferences` if the `dotnet pack` command is executed with `--no-build` parameter

**Comment by alirezanet** [comment]
Sure thanks.

**Comment by FabianTerhorst** [comment]
Since this change i have a problem publishing a C# CodeGen Package.
https://github.com/FabianTerhorst/coreclr-module/runs/5523504770?check_suite_focus=true
With 3.0.0 it works.

**Comment by alirezanet** [comment]
> Since this change i have a problem publishing a C# CodeGen Package. https://github.com/FabianTerhorst/coreclr-module/runs/5523504770?check_suite_focus=true With 3.0.0 it works.

Yeah, Looks like this PR have added more issues, I've had a few problems too
Until we fix this, use the `v3.0.0`.

**Comment by Kurounin** [comment]
Sorry about that. For my nugets (using latest dotnet 6.x) it works fine.
@FabianTerhorst seems that `dotnet pack` fails to build properly. @alirezanet since my issue was that running `pack` before `build` was missing some dlls, maybe an extra flag `SKIP_BUILD` which by default would be false (so it doesn't break existing actions) would solve this?

**Comment by Kurounin** [comment]
I created a new PR with the fix https://github.com/alirezanet/publish-nuget/pull/3

**Pull request merged**
